apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: redis-container
    image: redis
  - name: memcached-container
    image: memcached
  - name: consul
    image: consul
